# Generated by Django 4.2.11 on 2024-03-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ideia')),
                ('type', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tipo')),
                ('participants', models.IntegerField(blank=True, null=True, verbose_name='Participantes')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Preço')),
                ('link', models.CharField(blank=True, max_length=50, null=True, verbose_name='Link')),
                ('key', models.CharField(blank=True, max_length=15, null=True, verbose_name='Chave')),
                ('acessibility', models.FloatField(blank=True, null=True, verbose_name='Acessibilidade')),
            ],
        ),
    ]
