# Generated by Django 4.2.11 on 2024-03-09 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDesafio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='acessibility',
            field=models.FloatField(blank=True, null=True, verbose_name='acessibility'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='activity',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='activity'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='key',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='key'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='link',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='link'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='participants',
            field=models.IntegerField(blank=True, null=True, verbose_name='participants'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='type'),
        ),
    ]
