# Generated by Django 4.2.11 on 2024-03-07 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ViaCepModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.IntegerField(verbose_name='Cep do usuário')),
                ('logradouro', models.CharField(blank=True, max_length=100, null='', verbose_name='Logradouro do usuário')),
                ('complemento', models.CharField(blank=True, max_length=100, null='', verbose_name='Complemento do usuário')),
                ('bairro', models.CharField(blank=True, max_length=100, null='', verbose_name='Bairro do Usuário')),
                ('localidade', models.CharField(blank=True, max_length=100, null='', verbose_name='Localidade do usuário')),
                ('uf', models.CharField(blank=True, max_length=100, null='', verbose_name='UF do usuário')),
            ],
        ),
    ]
