# Generated by Django 4.2.11 on 2024-03-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDia4', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viacepmodel',
            name='cep',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cep do usuário'),
        ),
        migrations.AlterField(
            model_name='viacepmodel',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento do usuário'),
        ),
        migrations.AlterField(
            model_name='viacepmodel',
            name='localidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Localidade do usuário'),
        ),
        migrations.AlterField(
            model_name='viacepmodel',
            name='logradouro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Logradouro do usuário'),
        ),
        migrations.AlterField(
            model_name='viacepmodel',
            name='uf',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='UF do usuário'),
        ),
    ]
